{
  "id": "CVE-2019-16249",
  "published": "2019-09-11T23:15:14",
  "modified": "2023-11-29T07:13:44.304926",
  "details": "OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "repo_url": "https://github.com/opencv/opencv",
  "cwes": [],
  "commits": [
    "4a7ca5a291038a773ea0b67eaf6fbed9ad72170b",
    "c12243cf4fccf5df7b0270a32883986b373dca7b"
  ]
}
