{
  "id": "CVE-2025-2999",
  "published": "2025-03-31T15:15:44",
  "modified": "2025-09-24T12:40:25.891302",
  "details": "A vulnerability was found in PyTorch 2.6.0. It has been rated as critical. Affected by this issue is the function torch.nn.utils.rnn.unpack_sequence. The manipulation leads to memory corruption. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L"
    }
  ],
  "repo_url": "https://github.com/pytorch/pytorch",
  "cwes": [],
  "commits": [
    "b9029fc4497a9453e76892c9cf56144add89faf7"
  ]
}
