{
  "id": "CVE-2024-32879",
  "published": "2024-04-24T20:15:07",
  "modified": "2024-04-26T02:04:22.989037",
  "details": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
  "repo_url": "https://github.com/python-social-auth/social-app-django",
  "cwes": [],
  "commits": [
    "836b974c67a6e0213f68eca4dc18a2d25494907b"
  ]
}
