{
  "id": "CVE-2020-26213",
  "published": "2020-11-06T17:15:12",
  "modified": "2023-11-29T08:18:35.856302",
  "details": "In teler before version 0.0.1, if you run teler inside a Docker container and encounter `errors.Exit` function, it will cause denial-of-service (`SIGSEGV`) because it doesn't get process ID and process group ID of teler properly to kills. The issue is patched in teler 0.0.1 and 0.0.1-dev5.1.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/kitabisa/teler",
  "cwes": [],
  "commits": [
    "218066443447eabe32a5383da820a3b7ceba6aef"
  ]
}
