{
  "id": "PSF-2012-6",
  "published": "2012-08-14T22:00:00",
  "modified": "2023-11-08T03:57:04.701909",
  "details": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
  "summary": "Vulnerability in the utf-16 decoder after error handling",
  "repo_url": "https://github.com/python/cpython",
  "cwes": [],
  "commits": [
    "3a833f748fc629d25a5af3faeef91447f4709804"
  ]
}
